In [19]:
import pandas as pd

file_path = "D:/Santai Coding/Pradigma - Digital Maintenance Portal/Data Migration/MaintenanceOrder_20260212100905.xlsx"

df = pd.read_excel(file_path, sheet_name="Data")
df.head(3)

,mtnorder_id,mtnorder_type,mtnorder_no,mtnorder_parent,notifictn_no,notifictn_sn,confirmtn_no,mtnorder_busno,mtnorder_desc,depot_id,...,dt_created,dt_modified,material_number,material_description,material_group,quantity,plan_start_date,plan_start_time,plan_finish_date,plan_finish_time
0,NaN,YPM1,4000695370,NaN,12492145,NaN,7439935,DPT-ACP,Air Receiver Tank 1500Ltrs,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-11-01,17:30:00,2025-11-01,17:30:00
1,NaN,YPM1,4000695370,NaN,12492145,NaN,7439936,DPT-ACP,Air Receiver Tank 1500Ltrs,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-11-01,17:30:00,2025-11-01,17:30:00
2,NaN,YPM1,4000706817,NaN,12514598,NaN,7500931,NaN,Power Supply Half-Year Servicing RSV004,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-10,08:30:00,2025-10-10,17:30:00

In [20]:
pm_rsd = df[(df["oper_workcenter"] == "RSDM") & (df["mtnorder_type"] == "YPM1")].head(4)
cm_rsd = df[(df["oper_workcenter"] == "RSDM") & (df["mtnorder_type"] == "YCM1")].head(4)

rsd = pd.concat([pm_rsd, cm_rsd])
rsd

,mtnorder_id,mtnorder_type,mtnorder_no,mtnorder_parent,notifictn_no,notifictn_sn,confirmtn_no,mtnorder_busno,mtnorder_desc,depot_id,...,dt_created,dt_modified,material_number,material_description,material_group,quantity,plan_start_date,plan_start_time,plan_finish_date,plan_finish_time
2,NaN,YPM1,4000706817,NaN,12514598,NaN,7500931,NaN,Power Supply Half-Year Servicing RSV004,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-10,08:30:00,2025-10-10,17:30:00
3,NaN,YPM1,4000706817,NaN,12514598,NaN,7500932,NaN,Power Supply Half-Year Servicing RSV004,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-10,08:30:00,2025-10-10,17:30:00
4,NaN,YPM1,4000706818,NaN,12514599,NaN,7500933,NaN,Power Supply Half-Year Servicing RSV006,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-10,08:30:00,2025-10-10,17:30:00
5,NaN,YPM1,4000706818,NaN,12514599,NaN,7500934,NaN,Power Supply Half-Year Servicing RSV006,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-10,08:30:00,2025-10-10,17:30:00
30,NaN,YCM1,4000709260,NaN,12518459,NaN,7513897,NaN,023AS-Guide wheel tire worn,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
31,NaN,YCM1,4000709501,NaN,12519200,NaN,7514330,NaN,ICA 3 RST Door 3 Door fault [08],NaN,...,2026-02-12 10:09:05,2025-10-02 15:02:29,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
38,NaN,YCM1,4000709981,NaN,12522674,NaN,7515700,NaN,021HS-Bogie assembly load tire worn,NaN,...,2026-02-12 10:09:05,2025-10-04 17:03:01,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
40,NaN,YCM1,4000710006,NaN,12522119,NaN,7516374,NaN,ECA 4 HVAC Supply Fan 1-2 High Speed Fau,NaN,...,2026-02-12 10:09:05,2025-10-02 14:56:27,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00

In [21]:
pm_psd = df[(df["oper_workcenter"] == "WS10") & (df["mtnorder_type"] == "YPM1")].head(4)
cm_psd = df[(df["oper_workcenter"] == "WS10") & (df["mtnorder_type"] == "YCM1")].head(4)

psd = pd.concat([pm_psd, cm_psd])
psd

,mtnorder_id,mtnorder_type,mtnorder_no,mtnorder_parent,notifictn_no,notifictn_sn,confirmtn_no,mtnorder_busno,mtnorder_desc,depot_id,...,dt_created,dt_modified,material_number,material_description,material_group,quantity,plan_start_date,plan_start_time,plan_finish_date,plan_finish_time
198,NaN,YPM1,4000711911,NaN,12524528,NaN,7527124,NaN,PM Inspection for Titiwangsa TPSS,NaN,...,2026-02-12 10:09:05,2025-10-17 10:29:20,NaN,NaN,NaN,1.0,2025-10-14,14:07:30,2025-10-14,17:30:00
201,NaN,YPM1,4000711912,NaN,12524527,NaN,7527125,NaN,PM Inspection for Medan Tuanku Station,NaN,...,2026-02-12 10:09:05,2025-10-17 10:29:35,NaN,NaN,NaN,1.0,2025-10-14,24:00:00,2025-10-14,24:00:00
202,NaN,YPM1,4000711913,NaN,12524526,NaN,7527126,NaN,PM Inspection for Bukit Nanas Station,NaN,...,2026-02-12 10:09:05,2025-10-17 10:30:05,NaN,NaN,NaN,1.0,2025-10-14,24:00:00,2025-10-14,24:00:00
1252,NaN,YPM1,4000726205,NaN,12548837,NaN,7599589,NaN,Quarterly Inspection for PA System BFN,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-11-26,17:30:00,2025-11-26,17:30:00
154,NaN,YCM1,4000711261,NaN,12522896,NaN,7523347,NaN,PIDS all station unable to set time hea,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-02,17:30:00,2025-10-02,17:30:00
261,NaN,YCM1,4000712453,NaN,12525607,NaN,7531660,NaN,A few units lamp unserviceable,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-09,17:30:00,2025-10-09,17:30:00
491,NaN,YCM1,4000716051,NaN,12528606,NaN,7548870,TSZ-AAR,AARU open,NaN,...,2026-02-12 10:09:05,2025-11-06 23:25:07,NaN,NaN,NaN,1.0,2025-10-16,17:30:00,2025-10-16,17:30:00
2408,NaN,YCM1,4000727264,NaN,12555692,NaN,7604222,NaN,Request to install 3 phase sockets,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-12-03,17:30:00,2025-12-03,17:30:00

In [22]:
pm_snc = df[(df["oper_workcenter"] == "WS20") & (df["mtnorder_type"] == "YPM1")].head(4)
cm_snc = df[(df["oper_workcenter"] == "WS20") & (df["mtnorder_type"] == "YCM1")].head(4)

snc = pd.concat([pm_snc, cm_snc])
snc

,mtnorder_id,mtnorder_type,mtnorder_no,mtnorder_parent,notifictn_no,notifictn_sn,confirmtn_no,mtnorder_busno,mtnorder_desc,depot_id,...,dt_created,dt_modified,material_number,material_description,material_group,quantity,plan_start_date,plan_start_time,plan_finish_date,plan_finish_time
39,NaN,YPM1,4000710004,NaN,12515868,NaN,7516360,000000000020005449,Quarterly Inspection for UPS System,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-02,17:30:00,2025-10-02,17:30:00
92,NaN,YPM1,4000710667,NaN,12522110,NaN,7519598,HAH-SCA,Quarterly Inspection for SCADA System,NaN,...,2026-02-12 10:09:05,2025-11-05 17:35:15,NaN,NaN,NaN,1.0,2025-10-04,17:30:00,2025-10-04,17:30:00
93,NaN,YPM1,4000710668,NaN,12521972,NaN,7519601,HAH-RCS,Quarterly Inspection for RADIO System,NaN,...,2026-02-12 10:09:05,2025-11-05 17:38:20,NaN,NaN,NaN,1.0,2025-10-04,17:30:00,2025-10-04,17:30:00
94,NaN,YPM1,4000710669,NaN,12522112,NaN,7519602,IBI-SCA,Quarterly Inspection for SCADA System,NaN,...,2026-02-12 10:09:05,2025-11-05 17:40:35,NaN,NaN,NaN,1.0,2025-10-05,17:30:00,2025-10-05,17:30:00
48,NaN,YCM1,4000710166,NaN,12520912,NaN,7517619,NaN,PAGS failure,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
49,NaN,YCM1,4000710167,NaN,12522113,NaN,7517620,NaN,PAGS Door ICA 2 RST Door 2 (DCU 5),NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
50,NaN,YCM1,4000710169,NaN,12522755,NaN,7517622,NaN,PAGS failure,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
51,NaN,YCM1,4000710170,NaN,12520911,NaN,7517623,NaN,ICA 3 Door 1 (DCU 6) red,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00

In [23]:
pm_tnm = df[(df["oper_workcenter"] == "TNM1") & (df["mtnorder_type"] == "YPM1")].head(4)
cm_tnm = df[(df["oper_workcenter"] == "TNM1") & (df["mtnorder_type"] == "YCM1")].head(4)

tnm = pd.concat([pm_tnm, cm_tnm])
tnm

,mtnorder_id,mtnorder_type,mtnorder_no,mtnorder_parent,notifictn_no,notifictn_sn,confirmtn_no,mtnorder_busno,mtnorder_desc,depot_id,...,dt_created,dt_modified,material_number,material_description,material_group,quantity,plan_start_date,plan_start_time,plan_finish_date,plan_finish_time
0,NaN,YPM1,4000695370,NaN,12492145,NaN,7439935,DPT-ACP,Air Receiver Tank 1500Ltrs,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-11-01,17:30:00,2025-11-01,17:30:00
1,NaN,YPM1,4000695370,NaN,12492145,NaN,7439936,DPT-ACP,Air Receiver Tank 1500Ltrs,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-11-01,17:30:00,2025-11-01,17:30:00
36,NaN,YPM1,4000709965,NaN,12522784,NaN,7516475,DPT-BDP,MONTHLY MECH. INSP. BOGIE DROP PIT 1,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-05,17:30:00,2025-10-05,17:30:00
37,NaN,YPM1,4000709965,NaN,12522784,NaN,7516476,DPT-BDP,MONTHLY MECH. INSP. BOGIE DROP PIT 1,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-05,17:30:00,2025-10-05,17:30:00
5288,NaN,YCM1,4000739509,NaN,12576329,NaN,7664652,SWT-SW2-NRM,Change motor non rumba,NaN,...,2026-02-12 10:09:05,2026-01-21 11:10:19,NaN,NaN,NaN,1.0,2026-01-17,17:30:00,2026-01-17,17:30:00
5391,NaN,YCM1,4000739821,NaN,12572214,NaN,7666504,SWT-SW8,SW8 maintenance work,NaN,...,2026-02-12 10:09:05,2026-01-21 11:34:00,NaN,NaN,NaN,1.0,2026-01-06,17:30:00,2026-01-06,17:30:00
5392,NaN,YCM1,4000739829,NaN,12574761,NaN,7666524,ML-GWB-FP-115,finger Plate 115,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2026-01-14,17:30:00,2026-01-14,17:30:00
5648,NaN,YCM1,4000743029,NaN,12573992,NaN,7683405,NaN,Finger plate 114 & 115,NaN,...,2026-02-12 10:09:05,2026-01-29 21:52:20,NaN,NaN,NaN,1.0,2026-01-12,17:30:00,2026-01-12,17:30:00

In [25]:
df = pd.concat([rsd, psd, snc, tnm], ignore_index=True)
df

,mtnorder_id,mtnorder_type,mtnorder_no,mtnorder_parent,notifictn_no,notifictn_sn,confirmtn_no,mtnorder_busno,mtnorder_desc,depot_id,...,dt_created,dt_modified,material_number,material_description,material_group,quantity,plan_start_date,plan_start_time,plan_finish_date,plan_finish_time
0,NaN,YPM1,4000706817,NaN,12514598,NaN,7500931,NaN,Power Supply Half-Year Servicing RSV004,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-10,08:30:00,2025-10-10,17:30:00
1,NaN,YPM1,4000706817,NaN,12514598,NaN,7500932,NaN,Power Supply Half-Year Servicing RSV004,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-10,08:30:00,2025-10-10,17:30:00
2,NaN,YPM1,4000706818,NaN,12514599,NaN,7500933,NaN,Power Supply Half-Year Servicing RSV006,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-10,08:30:00,2025-10-10,17:30:00
3,NaN,YPM1,4000706818,NaN,12514599,NaN,7500934,NaN,Power Supply Half-Year Servicing RSV006,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-10,08:30:00,2025-10-10,17:30:00
4,NaN,YCM1,4000709260,NaN,12518459,NaN,7513897,NaN,023AS-Guide wheel tire worn,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
5,NaN,YCM1,4000709501,NaN,12519200,NaN,7514330,NaN,ICA 3 RST Door 3 Door fault [08],NaN,...,2026-02-12 10:09:05,2025-10-02 15:02:29,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
6,NaN,YCM1,4000709981,NaN,12522674,NaN,7515700,NaN,021HS-Bogie assembly load tire worn,NaN,...,2026-02-12 10:09:05,2025-10-04 17:03:01,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
7,NaN,YCM1,4000710006,NaN,12522119,NaN,7516374,NaN,ECA 4 HVAC Supply Fan 1-2 High Speed Fau,NaN,...,2026-02-12 10:09:05,2025-10-02 14:56:27,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
8,NaN,YPM1,4000711911,NaN,12524528,NaN,7527124,NaN,PM Inspection for Titiwangsa TPSS,NaN,...,2026-02-12 10:09:05,2025-10-17 10:29:20,NaN,NaN,NaN,1.0,2025-10-14,14:07:30,2025-10-14,17:30:00
9,NaN,YPM1,4000711912,NaN,12524527,NaN,7527125,NaN,PM Inspection for Medan Tuanku Station,NaN,...,2026-02-12 10:09:05,2025-10-17 10:29:35,NaN,NaN,NaN,1.0,2025-10-14,24:00:00,2025-10-14,24:00:00
10,NaN,YPM1,4000711913,NaN,12524526,NaN,7527126,NaN,PM Inspection for Bukit Nanas Station,NaN,...,2026-02-12 10:09:05,2025-10-17 10:30:05,NaN,NaN,NaN,1.0,2025-10-14,24:00:00,2025-10-14,24:00:00
11,NaN,YPM1,4000726205,NaN,12548837,NaN,7599589,NaN,Quarterly Inspection for PA System BFN,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-11-26,17:30:00,2025-11-26,17:30:00
12,NaN,YCM1,4000711261,NaN,12522896,NaN,7523347,NaN,PIDS all station unable to set time hea,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-02,17:30:00,2025-10-02,17:30:00
13,NaN,YCM1,4000712453,NaN,12525607,NaN,7531660,NaN,A few units lamp unserviceable,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-09,17:30:00,2025-10-09,17:30:00
14,NaN,YCM1,4000716051,NaN,12528606,NaN,7548870,TSZ-AAR,AARU open,NaN,...,2026-02-12 10:09:05,2025-11-06 23:25:07,NaN,NaN,NaN,1.0,2025-10-16,17:30:00,2025-10-16,17:30:00
15,NaN,YCM1,4000727264,NaN,12555692,NaN,7604222,NaN,Request to install 3 phase sockets,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-12-03,17:30:00,2025-12-03,17:30:00
16,NaN,YPM1,4000710004,NaN,12515868,NaN,7516360,000000000020005449,Quarterly Inspection for UPS System,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-02,17:30:00,2025-10-02,17:30:00
17,NaN,YPM1,4000710667,NaN,12522110,NaN,7519598,HAH-SCA,Quarterly Inspection for SCADA System,NaN,...,2026-02-12 10:09:05,2025-11-05 17:35:15,NaN,NaN,NaN,1.0,2025-10-04,17:30:00,2025-10-04,17:30:00
18,NaN,YPM1,4000710668,NaN,12521972,NaN,7519601,HAH-RCS,Quarterly Inspection for RADIO System,NaN,...,2026-02-12 10:09:05,2025-11-05 17:38:20,NaN,NaN,NaN,1.0,2025-10-04,17:30:00,2025-10-04,17:30:00
19,NaN,YPM1,4000710669,NaN,12522112,NaN,7519602,IBI-SCA,Quarterly Inspection for SCADA System,NaN,...,2026-02-12 10:09:05,2025-11-05 17:40:35,NaN,NaN,NaN,1.0,2025-10-05,17:30:00,2025-10-05,17:30:00
20,NaN,YCM1,4000710166,NaN,12520912,NaN,7517619,NaN,PAGS failure,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
21,NaN,YCM1,4000710167,NaN,12522113,NaN,7517620,NaN,PAGS Door ICA 2 RST Door 2 (DCU 5),NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
22,NaN,YCM1,4000710169,NaN,12522755,NaN,7517622,NaN,PAGS failure,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
23,NaN,YCM1,4000710170,NaN,12520911,NaN,7517623,NaN,ICA 3 Door 1 (DCU 6) red,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-09-30,17:30:00,2025-09-30,17:30:00
24,NaN,YPM1,4000695370,NaN,12492145,NaN,7439935,DPT-ACP,Air Receiver Tank 1500Ltrs,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-11-01,17:30:00,2025-11-01,17:30:00
25,NaN,YPM1,4000695370,NaN,12492145,NaN,7439936,DPT-ACP,Air Receiver Tank 1500Ltrs,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-11-01,17:30:00,2025-11-01,17:30:00
26,NaN,YPM1,4000709965,NaN,12522784,NaN,7516475,DPT-BDP,MONTHLY MECH. INSP. BOGIE DROP PIT 1,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-05,17:30:00,2025-10-05,17:30:00
27,NaN,YPM1,4000709965,NaN,12522784,NaN,7516476,DPT-BDP,MONTHLY MECH. INSP. BOGIE DROP PIT 1,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2025-10-05,17:30:00,2025-10-05,17:30:00
28,NaN,YCM1,4000739509,NaN,12576329,NaN,7664652,SWT-SW2-NRM,Change motor non rumba,NaN,...,2026-02-12 10:09:05,2026-01-21 11:10:19,NaN,NaN,NaN,1.0,2026-01-17,17:30:00,2026-01-17,17:30:00
29,NaN,YCM1,4000739821,NaN,12572214,NaN,7666504,SWT-SW8,SW8 maintenance work,NaN,...,2026-02-12 10:09:05,2026-01-21 11:34:00,NaN,NaN,NaN,1.0,2026-01-06,17:30:00,2026-01-06,17:30:00
30,NaN,YCM1,4000739829,NaN,12574761,NaN,7666524,ML-GWB-FP-115,finger Plate 115,NaN,...,2026-02-12 10:09:05,0000-00-00,NaN,NaN,NaN,1.0,2026-01-14,17:30:00,2026-01-14,17:30:00
31,NaN,YCM1,4000743029,NaN,12573992,NaN,7683405,NaN,Finger plate 114 & 115,NaN,...,2026-02-12 10:09:05,2026-01-29 21:52:20,NaN,NaN,NaN,1.0,2026-01-12,17:30:00,2026-01-12,17:30:00

In [26]:
df.to_csv(
    "NOTIFICATION_BLK_202603030000.txt",
    sep="|",
    index=False,
    header=True,
    encoding="utf-8"
)